### ISSUE TITLE
Support Multiple Consoles

### ISSUE THREAD

**Issue by sassa4ras** [neilenns/ambientweather2mqtt#108]
Hello,

So I have two consoles connected to one weather station. Since the console will publish a temperature and humidity setting, if I have two consoles both reporting to AWNET2MQTT, the values get updated to the same published entity. What ends up happening is the recorded temperature swings back and forth between the two values as each is published. 

Is there a way to make it so each console gets its own sensor entity? 

Thanks

**Comment by neilenns** [comment]
Can you explain your weather station setup in more detail? You have just one weather station but two display consoles? When you configured the reporting URL did you do it on both consoles or just one?

The only identifying information I receive in the data is a "passkey", and that is used to create separate entities already. If you are seeing the values flip back and forth with two consoles it sounds like it's because they are both sending data using the same passkey (which I believe is unique to the weather station, not the console).

**Comment by sassa4ras** [comment]
Sorry it took me so long to get back to you.

My setup is ONE outdoor unit, but two WS-2902 consoles. One in the kitchen and one in the garage. Essentially, the only value that would differ between the two is the "indoor" temp each reports. I had both consoles configured to report, which is probably why I was seeing the temp cycle back and forth. If each is sending the same "passkey" then the integration would assume the "indoor" temp is coming from the same console. 

Is there a way for the console to report a unique value that would allow both "indoor" temp entities to co-exist?

**Comment by neilenns** [comment]
I don't receive any data that indicates consoles. I only receive data that indicates which weather station (the passkey).

In your situation I suggest configuring only one console to send data, not both.

**Comment by sassa4ras** [comment]
I figured as much, which is what I've done. Thanks for the help!
